name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    - name: Archive production artifacts
      run: tar -czvf react_beachfront_project ./build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: react_beachfront_project
        path: ./react_beachfront_project

    - name: List contents of tar file
      run: tar -tvf react_beachfront_project  

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: react_beachfront_project
        path: .

    - name: Upload artifacts and extract
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        port: 22
        script: |
          scp -v $GITHUB_WORKSPACE/react_beachfront_project /tmp/
          rm -rf /var/www/react_beachfront_project/ || true
          mkdir -p /var/www/react_beachfront_project/
          tar -xzvf /tmp/react_beachfront_project -C /var/www/react_beachfront_project 
          sudo systemctl restart nginx
